### THIS REQUEST INITIATES/RESTARTS THE TWITTER FEED ###
GET http://localhost:3001/live_stream_tweets.json

### THIS REQUEST CALLS THE CONTENT IN THE OUT.TXT FILE AND RETURNS JSON ###
GET http://localhost:3001/live_stream_echos
